# frozen_string_literal: true

Vagrant.configure('2') do |config|
  config.vm.box = 'generic/freebsd12'
  config.vm.provision "shell", inline: <<-SHELL
    pkg install -y gtar
  SHELL
end

common = '../common'
load common if File.exist?(common)
