# frozen_string_literal: true

Vagrant.configure('2') do |config|
  config.vm.box = 'generic/ubuntu2204'
  config.vm.define 'wizard'

  config.vm.provision 'shell', path: 'bootstrap'

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 4
    libvirt.memory = 4096
  end

  config.vm.synced_folder '.', '/vagrant', disabled: true

  # config.vm.provision 'ansible' do |ansible|
  #   ansible.config_file = '../../ansible.cfg'
  #   ansible.playbook = '../../run_all.yml'
  # end

  # same as above, to run the steps separately

  config.vm.provision 'ansible' do |provdep|
    provdep.config_file = '../../../ansible.cfg'
    provdep.playbook = '../../../provision_dependencies.yml'
  end

  config.vm.provision 'ansible' do |provtest|
    provtest.config_file = '../../../ansible.cfg'
    provtest.playbook = '../../../provision_test_suite.yml'
  end

  config.vm.provision 'ansible' do |preptest|
    preptest.config_file = '../../../ansible.cfg'
    preptest.playbook = '../../../prepare_tests.yml'
  end

  # config.vm.provision 'ansible' do |runtests|
  #   runtests.config_file = '../../../ansible.cfg'
  #   runtests.playbook = '../../../run_tests.yml'
  # end
end
