# we measure coverage but don't enforce it
# https://docs.codecov.com/docs/codecov-yaml
coverage:
  status:
    patch:
      default:
        target: 0%
    project:
      default:
        target: 0%
ignore:
  - "pkg/modelscapi"
  - "pkg/models"
  - "pkg/database/ent"
