version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "kind/dependencies"
      - "github-actions"
    groups:
      github-actions:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "kind/dependencies"
      - "go"
    groups:
      gomod:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "uv"
    directory: "/build/docker/test"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "kind/dependencies"
      - "python"
    groups:
      uv:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directories:
      - "/build/docker"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "kind/dependencies"
      - "docker"
    groups:
      docker:
        update-types:
          - "minor"
          - "patch"
