categories:
  - title: 'New Features'
    labels:
      - 'new feature'
      - 'kind/feature'
  - title: 'Improvements'
    labels:
      - 'kind/enhancement'
      - 'enhancement'
      - 'improvement'
  - title: 'Bug Fixes'
    labels:
      - 'kind/fix'
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Documentation'
    labels:
      - 'documentation'
      - 'doc'
  - title: 'Chore / Deps'
    labels:
      - 'kind/dependencies'
      - 'kind/chore'
tag-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  ## Changes

  $CHANGES

  ## Geolite2 notice

  This product includes GeoLite2 data created by MaxMind, available from <a href="https://www.maxmind.com">https://www.maxmind.com</a>.
  
  ## Installation

  Take a look at the [installation instructions](https://doc.crowdsec.net/docs/getting_started/install_crowdsec).
  
