categories:
  - title: 'New Features'
    labels:
      - 'new feature'
  - title: 'Improvments'
    labels:
      - 'enhancement'
      - 'improvment'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Documentation'
    labels:
      - 'documention'
      - 'doc'
tag-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  ## Changes

  $CHANGES

  ## Geolite2 notice

  This product includes GeoLite2 data created by MaxMind, available from <a href="https://www.maxmind.com">https://www.maxmind.com</a>.
  