# frozen_string_literal: true

Vagrant.configure('2') do |config|
  config.vm.box = 'generic/hardenedbsd13'
  config.vm.provision "shell", inline: <<-SHELL
    sudo pkg install python3
  SHELL
end

common = '../../common'
load common if File.exist?(common)
