// Code generated by go-swagger; DO NOT EDIT.

package modelscapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MetricsRequestMachinesItem MetricsAgentInfo
//
// swagger:model MetricsRequestMachinesItem
type MetricsRequestMachinesItem struct {

	// last agent push date
	LastPush string `json:"last_push,omitempty"`

	// last agent update date
	LastUpdate string `json:"last_update,omitempty"`

	// agent name
	Name string `json:"name,omitempty"`

	// agent version
	Version string `json:"version,omitempty"`
}

// Validate validates this metrics request machines item
func (m *MetricsRequestMachinesItem) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this metrics request machines item based on context it is used
func (m *MetricsRequestMachinesItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MetricsRequestMachinesItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetricsRequestMachinesItem) UnmarshalBinary(b []byte) error {
	var res MetricsRequestMachinesItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
