#!/bin/bash

# shellcheck disable=SC1007
THIS_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
# shellcheck disable=SC1091
. "${THIS_DIR}/.environment.sh"

online_api_credentials="$(dirname "${CONFIG_YAML}")/online_api_credentials.yaml"
export online_api_credentials

yq e '.api.server.online_client.credentials_path=strenv(online_api_credentials)' -i "${CONFIG_YAML}"
