#!/usr/bin/env bash

#shellcheck disable=SC1007
THIS_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
cd "${THIS_DIR}"

case "$DB_BACKEND" in
    sqlite)
        ./instance-sqlite "$@"
        ;;
    mysql)
        ./instance-mysql "$@"
        ;;
    *)
        echo >&2 "unknown $DB_BACKEND"
        exit 1
        ;;
esac;
