#!/usr/bin/env bash

#shellcheck disable=SC1007
THIS_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
cd "${THIS_DIR}"
#shellcheck disable=SC1090
. ./.environment.sh

backend_script="./lib/config/config-${CONFIG_BACKEND}"

if [ ! -x "$backend_script" ]; then
    echo "unknown config backend '$CONFIG_BACKEND'" >&2
    exit 1
fi

exec "$backend_script" "$@"
