# frozen_string_literal: true

Vagrant.configure('2') do |config|
  config.vm.box = 'fedora/36-cloud-base'
  config.vm.provision "shell", inline: <<-SHELL
    # sudo dnf -y update
  SHELL
end

common = '../common'
load common if File.exist?(common)
