openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key


paths:
  /apikey:
    get:
      summary: test API key auth
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: OK