openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic


paths:
  /basic:
    get:
      summary: test basic auth
      security:
        - BasicAuth: []
      responses:
        "200":
          description: OK