common = '../Vagrantfile.common'
load common if File.exists?(common)

Vagrant.configure("2") do |config|
  # the official boxes seem to have issues with journalctl
  # config.vm.box = "fedora/36-cloud-base"
  config.vm.box = "generic/fedora36"
end
