# frozen_string_literal: true

Vagrant.configure('2') do |config|
  config.vm.box = 'generic/ubuntu1604'
  config.vm.provision "shell", inline: <<-SHELL
  SHELL
end

common = '../common'
load common if File.exist?(common)
