# frozen_string_literal: true

Vagrant.configure('2') do |config|
  config.vm.box = 'debian/stretch64'
  config.vm.provision "shell", inline: <<-SHELL
    sudo sed -i s/httpredir.debian.org/archive.debian.org/g /etc/apt/sources.list
  SHELL
end

common = '../common'
load common if File.exist?(common)
