// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ConsoleOptions ConsoleOptions
//
// swagger:model ConsoleOptions
type ConsoleOptions []string

// Validate validates this console options
func (m ConsoleOptions) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this console options based on context it is used
func (m ConsoleOptions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
