// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// DeleteDecisionResponse DeleteDecisionResponse
//
// swagger:model DeleteDecisionResponse
type DeleteDecisionResponse []string

// Validate validates this delete decision response
func (m DeleteDecisionResponse) Validate(formats strfmt.Registry) error {
	return nil
}
