// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FlushDecisionResponse FlushDecisionResponse
//
// swagger:model FlushDecisionResponse
type FlushDecisionResponse struct {

	// decision id
	DecisionID string `json:"decision_id,omitempty"`
}

// Validate validates this flush decision response
func (m *FlushDecisionResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FlushDecisionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FlushDecisionResponse) UnmarshalBinary(b []byte) error {
	var res FlushDecisionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
