# frozen_string_literal: true

Vagrant.configure('2') do |config|
  config.vm.box = "opensuse/Leap-15.6.x86_64"
  config.vm.provision "shell", inline: <<-SHELL
  SHELL
end

common = '../common'
load common if File.exist?(common)
