# frozen_string_literal: true

Vagrant.configure('2') do |config|
  config.vm.box = 'generic/centos8s'
  config.vm.provision "shell", inline: <<-SHELL
    sudo dnf -y install dnf-plugins-core kitty-terminfo
    dnf config-manager --set-enabled powertools
    # sudo dnf -y update
  SHELL
end

common = '../common'
load common if File.exist?(common)
