# frozen_string_literal: true

Vagrant.configure('2') do |config|
  config.vm.box = 'generic/oracle8'
  config.vm.provision 'shell', path: 'bootstrap'
end

common = '../common'
load common if File.exist?(common)
