# frozen_string_literal: true

Vagrant.configure('2') do |config|
  config.vm.box = 'generic/centos9s'
  config.vm.provision "shell", inline: <<-SHELL
    sudo dnf -y install dnf-plugins-core
    sudo dnf config-manager --set-enabled crb
  SHELL
end

common = '../common'
load common if File.exist?(common)
