# frozen_string_literal: true

Vagrant.configure('2') do |config|
  # config.vm.box = 'fedora/35-cloud-base'
  config.vm.box = 'generic/fedora35'
  config.vm.provision "shell", inline: <<-SHELL
  SHELL
end

common = '../common'
load common if File.exist?(common)
