# frozen_string_literal: true

Vagrant.configure('2') do |config|
  config.vm.box = 'generic/ubuntu2204'
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt install -y kitty-terminfo
  SHELL
end

common = '../common'
load common if File.exist?(common)
