# frozen_string_literal: true

Vagrant.configure('2') do |config|
  config.vm.box = 'cloudnatives/amazon-linux-2'
  config.vm.define 'crowdsec'

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 1
    libvirt.memory = 1536
  end

  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provision 'ansible' do |ansible|
    ansible.config_file = '../../../ansible.cfg'
    ansible.playbook = '../../../run_all.yml'
  end
end
