Vagrant.configure("2") do |config|
  # the official boxes seem to have issues with journalctl
  # config.vm.box = "fedora/35-cloud-base"
  config.vm.box = "generic/fedora35"
end

common = '../Vagrantfile.common'
load common if File.exists?(common)
