name: build-msi (windows)

on:
  release:
    types:
      - prereleased
  push:
    branches:
      - master
      - releases/**
    paths:
      - build/windows/installer/*.wxs
      - .github/workflows/ci-windows-build-msi.yml
  pull_request:
    branches:
      - master
      - releases/**
    paths:
      - build/windows/installer/*.wxs
      - .github/workflows/ci-windows-build-msi.yml

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 0
        submodules: false
        persist-credentials: false

    - name: "Set up Go"
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: go.mod

    - name: Build
      run: make windows_installer BUILD_RE2_WASM=1
    - name: Upload MSI
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        path: crowdsec*msi
        name: crowdsec.msi
