name: bats / functional tests with PostgreSQL

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: "Build the application"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready -u postgres
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:

    - name: "Force machineid"
      run: |
          sudo chmod +w /etc/machine-id
          echo githubciXXXXXXXXXXXXXXXXXXXXXXXX | sudo tee /etc/machine-id

    - name: "Set up Go 1.17"
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
      id: go

    - name: "Clone CrowdSec"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    - name: "Install bats dependencies"
      run: |
        sudo apt install -qq daemonize netcat-openbsd
        GO111MODULE=on go get github.com/mikefarah/yq/v4

    - name: "BATS: build crowdsec (DB_BACKEND: pgx)"
      run: make clean bats-build || true
      env:
        DB_BACKEND: pgx
        PGHOST: 127.0.0.1
        PGPORT: 5432
        PGPASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        PGUSER: postgres

    - name: "BATS: run tests (DB_BACKEND: pgx)"
      run: make bats-test || true
      env:
        DB_BACKEND: pgx
        PGHOST: 127.0.0.1
        PGPORT: 5432
        PGPASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        PGUSER: postgres

    - name: "BATS: build crowdsec (DB_BACKEND: postgres)"
      run: make clean bats-build || true
      env:
        DB_BACKEND: postgres
        PGHOST: 127.0.0.1
        PGPORT: 5432
        PGPASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        PGUSER: postgres

    - name: "BATS: run tests (DB_BACKEND: postgres)"
      run: make bats-test || true
      env:
        DB_BACKEND: postgres
        PGHOST: 127.0.0.1
        PGPORT: 5432
        PGPASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        PGUSER: postgres

    - name: "show postgres logs"
      run: docker logs "${{ job.services.postgres.id }}"
      if: ${{ always() }}

