name: bats / functional tests with sqlite

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: "Build the application"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:

    - name: "Force machineid"
      run: |
          sudo chmod +w /etc/machine-id
          echo githubciXXXXXXXXXXXXXXXXXXXXXXXX | sudo tee /etc/machine-id

    - name: "Set up Go 1.17"
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
      id: go

    - name: "Clone CrowdSec"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    - name: "Install bats dependencies"
      run: |
        sudo apt install -qq daemonize netcat-openbsd
        GO111MODULE=on go get github.com/mikefarah/yq/v4
        go install github.com/wadey/gocovmerge@latest

    - name: "BATS: build crowdsec and fixture"
      run: TEST_COVERAGE=true make bats-clean bats-build bats-fixture

    - name: "BATS: run tests (with coverage)"
      run: TEST_COVERAGE=true make bats-test
