name: golangci-lint

on:
  push:
    tags:
      - v*
    branches:
      - master
      - releases/**
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'README.md'
jobs:
  golangci:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2022]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50
          args: --issues-exit-code=1 --timeout 10m
          only-new-issues: false
