name: tests

#those env variables are for localstack, so we can emulate aws services
env:
  AWS_HOST: localstack
  SERVICES: cloudwatch,logs 
  #those are to mimic aws config
  AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE 
  AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY 
  AWS_REGION: us-east-1 
  #and to override our endpoint in aws sdk
  AWS_ENDPOINT_FORCE: http://localhost:4566 

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'README.md'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Build
      run: make build && go get -u github.com/jandelgado/gcov2lcov
    - name: All tests
      run: go test -coverprofile=coverage.out -covermode=atomic ./...
    - name: gcov2lcov
      uses: jandelgado/gcov2lcov-action@v1.0.2
      with:
        infile: coverage.out
        outfile: coverage.txt
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.txt