name: golangci-lint-windows
on:
  push:
    tags:
      - v*
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'README.md'
jobs:
  golangci:
    name: lint-windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.45.2
          # Optional: golangci-lint command line arguments.
          args: --issues-exit-code=0 --timeout 10m
          only-new-issues: true


