name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'README.md'
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.45
          # Optional: golangci-lint command line arguments.
          args: --issues-exit-code=1 --timeout 5m
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: false
          # Optional: if set to true then the all caching functionality will be complete disabled,
          #           takes precedence over all other caching options.
          skip-cache: false
          # Optional: if set to true then the action don't cache or restore ~/go/pkg.
          skip-pkg-cache: false
          # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
          skip-build-cache: false

