name: Hub-CI

on:
  push:
    branches: [ functional_basic_tests ]
  pull_request:
    branches: [ functional_basic_tests ]

jobs:
  build:
    name: Install generated release and perform basic tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Build release
      run: BUILD_VERSION=xxx make release
    - name: Install release
      run: |
        cd crowdsec-xxx
        ./wizard.sh --bininstall
    # - name: Cache release
    #   uses: actions/cache@v2
    #   id: cache
    #   with:
    #     path: crowdsec-xxx
    #     key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}