name: Hub-CI

on:
  push:
    branches: [ functional_basic_tests ]
  pull_request:
    branches: [ functional_basic_tests ]

jobs:
  build:
    name: Install generated release and perform basic tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Build release
      run: BUILD_VERSION=xxx make release
    - name: Install release
      run: |
        cd crowdsec-xxx
        sudo ./wizard.sh --bininstall
    - name: Install collection
      run: |
        cscli list -a
        sudo cscli install parser crowdsecurity/syslog-logs crowdsecurity/sshd-logs crowdsecurity/dateparse-enrich
        sudo cscli install scenario crowdsecurity/ssh-bf
    - name: Crowdsec Startup check
      run: |
        sudo crowdsec -c /etc/crowdsec/config/user.yaml -t 
    # - name: Cscli ban tests
    #   run: |
    #     sudo cscli ban list -o json
    #     sudo cscli ban list 
