on:
  push:
    branches:
      - gh_pages_deploy
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/deploy_doc.yml'
name: Deploy documentation
jobs:
  build:
    name: Deploy documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #CUSTOM_DOMAIN: optionaldomain.com