name: Dispatch to hub when creating pre-release

on: 
  release:
    types: prereleased

jobs:
  dispatch:
    name: dispatch to hub-tests
    runs-on: ubuntu-latest
    steps:
      - id: keydb
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: crowdsecurity
          repo: crowdsec
          excludes: prerelease, draft
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          event-type: create_branch
          repository: crowdsecurity/hub
          client-payload: '{"version": "${{ steps.keydb.outputs.release }}"}'
