name: Dispatch when pre-release

on:
  push:
    tags:
      - v*
    branches:
      - add_new_workflow
  release:
    types: prereleased

jobs:
  dispatch:
    name: dispatch to hub-tests
    runs-on: ubuntu-latest
    steps:
      - name: Invoke workflow in another repo with inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: create_tag
          repo: crowdsecurity/hub-tests
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: '{ "tag": "blah blah"}'
      - name: test
        run: echo "${{ github.ref }} / ${{ github.head_ref }} "