name: (push-master) Update Docker Hub README

on:
  push:
    branches:
      - master
    paths:
      - 'build/docker/README.md'

permissions:
  contents: read

jobs:
  update-docker-hub-readme:
    runs-on: ubuntu-latest
    steps:

      -
        name: Check out the repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        if: ${{ github.repository_owner == 'crowdsecurity' }}
        with:
          persist-credentials: false

      -
        name: Update docker hub README
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
        if: ${{ github.repository_owner == 'crowdsecurity' }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: crowdsecurity/crowdsec
          short-description: "Crowdsec - An open-source, lightweight agent to detect and respond to bad behaviours."
          readme-filepath: "./build/docker/README.md"
